sudo: required
language: rust
rust:
  - nightly
#  - beta
#  - 1.3.0
os:
  - linux
  - osx

env:
  global:
    # Don't export a nightly feature flag to Cargo
    # (since we're currently building against nightly only)
    - TRAVIS_CARGO_NIGHTLY_FEATURE=""
    - secure: irv+bqxTUDhYjoEsFhAujf76MuzGUnbOTLCbyeUSfM28OQPqVNkp136MAIB9gz+OexD+UOeDP/CaobSUl5i/+22Utq/F93YQ8oBmRNFVHAhdE87NY0LxQwDlKPQhUQ+/R1Cv3adCR0++Tqmdd/PczCYHWsmF5ZNqA35g2590aTw9TTIjWTvhj1uknx3TBjag6t47hmO5uFjtaYvI7uOMN6e+Cs7f1Bi1vMd0MT7MQHkjw9h3E6mM4hScY3otWicaGCSzQ2yNuSIMDf1gj+YmWbvE3s7z1EsSQ20/e+Q7/P02yAoqq1Z6zURPpfZvINgbgQeVXv0sFocExnrG9raA+sbtFvyhBJzB2uLKNa1JJ4+dEPfd7yWndT/4zZTUYDNc40nu5GVgqgF/YSs4JhGDOD9FMXx9tjgFYvilx22txwPP7TP7cbQq8fulCDWvYy71VjsVWl0bZAm94uHbobhuq+X0jwio4C76t04ybkIgGfhsc0xD+ZMiRyxI3knNZ/pBwGFnqjsOkLc3ra3mhlSZtycCz/GUhwFmitrMqUos5BRnfRPfDjCsHZS6Vag85wO31Kp/aWaSHZkyFDqQMm3OfC4etGjfS7LyQOdNZUBs242WkHB42yNuUiPDyx2aefRM7jyZAD7yewPuXwLTnx6p/LjKCMLtZvdATR8aMtOyraU=
  matrix:
    - LLVM_VERSION=3.7
    - LLVM_VERSION=3.6

matrix:
  allow_failures:
#    - rust: beta
#    - rust: 1.3.0
    - env: LLVM_VERSION=3.6
      os: linux
    - os: osx
  fast_finish: true
  exclude:
    - os: osx
      env: LLVM_VERSION=3.7

addons:
  apt:
    sources:
      # LLVM
      - llvm-toolchain-precise
      - llvm-toolchain-precise-3.6
      - llvm-toolchain-precise-3.7
      - ubuntu-toolchain-r-test
    packages:
      # Necessary for travis-cargo coverage reporting
      - libcurl4-openssl-dev
      - libelf-dev
      - libdw-dev
      # Required for building LLVM
      #- cmake
      - libstdc++6
      - g++-4.8
      # required for linking against LLVM
      - libedit-dev
      # LLVM
      - libllvm3.6
      - libllvm3.6-dbg
      - llvm-3.6
      - llvm-3.6-dev
      - libllvm3.7
      - libllvm3.7-dbg
      - llvm-3.7
      - llvm-3.7-dev

before_install:
  # install a newer cmake since at this time Travis only has version 2.8.7
  # all of this is Linux-only
  - |
      if [ $TRAVIS_OS_NAME = linux ]; then
        yes | sudo add-apt-repository ppa:kalakris/cmake &&
        sudo apt-get update -qq
      fi

install:
  # install travis-cargo script
  - pip install 'travis-cargo<0.2' --user
  # big blob of tasks to do on Loonix only:
  #   - install the correct CMake version (this step is why we require sudo).
  #   - link correct LLVM config executable
  #   - put the LLVM binaries on the PATH
  #   - set the C++ compiler to the version of g++ we installed earlier
  - |
      if [ $TRAVIS_OS_NAME = linux ]; then
        sudo apt-get install libXxf86vm-dev cmake &&
        ln -s /usr/bin/llvm-config-$LLVM_VERSION $HOME/.local/bin/llvm-config &&
        export PATH=$HOME/.local/bin:$PATH &&
        export CXX="g++-4.8"
      fi
  # if on OS X:
  #   - install LLVM from Homebrew
  #   - put it on the PATH
  - |
      if [ $TRAVIS_OS_NAME = osx ]; then
        brew update &&
        brew install llvm &&
        export PATH=/usr/local/opt/llvm/bin/:$PATH &&
        echo $PATH
      fi
  # checks to ensure that our LLVM is sane
  # (this is for debugging if the build fails)
  - which llvm-config
  - llvm-config --version

script:
  - travis-cargo build
  # test main and subcrates
  - |
      travis-cargo test &&
      cargo test -p mnemosyne &&
      cargo test -p mnemosyne-parser
  # run benchmarks (pending)
  - travis-cargo bench

after_success:
  # report test coverage to coveralls.io (Linux only)
  - |
      if [ $TRAVIS_OS_NAME = linux ]; then
        travis-cargo coveralls --no-sudo
      fi
  # report coverage to codecov.io
  - bash <(curl https://codecov.io/bash)

# triggers only on deploy (tagged commit)
before_deploy:
  # generate and upload Rustdoc to GitHub releases
  - travis-cargo doc && travis-cargo doc-upload
  # Build the release (optimized) Manganese executable
  - travis-cargo build -- --release
deploy:
  provider: releases
  api_key:
    secure: XBpVoJJ2XXk4yrjk5n2KrZEqgsnhv2LofQad36jiy+ex5hym/vN7GIxbfwZNxGwwADvWJV2J9kA4yDm1DpWfswAVKXmGM9CKmmlYB19jrOQ/a6eOfvUtX3Lb6CkZTdczpR8xu5j5k0gNUH2s5kCs2+IcRVN2iKwe1AidfYbNyEEwixMEjzVC29dXuPD7edksWc/puZjeleq6UBwPTi9UyjddlIxtgeKXb+eaPhQ0liyl4V4tg54WCwM96w0TJf4/hIE32LapliGU2nwyAlq6GSOe/3VA9ga/3KkETPF+jvfObC4KN23ivl+1D9AvKRODYVpHuJJY+N3P8NoX/Ylhp+G0n590Ew+7v0iQv2CtBrU+JDY5o0y89xhX8L3vZYtIHTy+8EhoJP8vpCLt69qRMX1aZutd2mxxvQThLQztuxgxKXMc4t6lEyhjBMWVZqxKT159u+8/PLJVUF9mLuZ7QaAYq6EZ9a3Zxkj7YjGJq62qqV6k49Z3pSMHd7xefvPm3tcNbVSeLepm1IMTFscx05Iio0rS0hoQUQBzVeTziwzpHTEXwlqAO//mbfQBC+aY9oRKc8BEimAm07CbSSjSoNaCReY6N1g8vyx++ziNcTYoJatxt5uv9C2rzdnCRLskGM4dIjANcvQ4YYf82S1B/ZkahB4WZrWa9QU+ihqzcTY=
  file: target/release/mn
  on:
    repo: hawkw/mnemosyne
    # release only on Git tags
    tags: true


notifications:
  slack:
    secure: mrlFRtLb4nlX638iOiaeXU07mEz1LicgPaJ6o9zivwfS8N4NGlmCHxBrMgrFRlP7FCgb1suWOYHFwKnUw385PcZB9Moi3WjaaDsBrH8Ip+unHsW6n7PkcuHRIrlyaffH5hUaIt+gPBze4QZtonjDIB4TnvpmPWUbuAEzolQJvTfIp6est4LBnH84D85rzIAF3ItEwG+GWmCqkD/yjD+mLmkPsGUvYwrPx7Ymd9mfN0bCPsp4+TUeDTDBRzMNe6RGshlCj7UyhNpIiRml2LtDOZoTAsRxQreU3c+SDcB8n4vhCoR21bOKmM7Gu0dYAHQPRdMJ9emC7yILUbwGpORZuCwDHAwKHpmw1Kn3kQMC8JKTyz6To8aOTBKUee6CaEshI8iMAFuKUroF14AhFen0JYfFVI6YDa8ZemShKKF5L8Z2XwPgaedXoHOSyopCrqPsxO5TKwLGe9RWiE5+Jg8SONtiaswfYb5D9/RvLz25Gw51AGScpz+txdJfl9+JJ5OZVerKYf5MdA6XH2E4AOG3D1BSR4GpY80nBG6C3FbhaxVmnebtUMTguX+wXAnNVqu3hFy/vjYTVBEknoNEAbvbwrx4wLndxkjs4vuLJtWianClEIwn3AgshAn9QE0585lp2c4Mal9r8uVEZ6u3HcH2OE+GZT+5pZNBbwKSnuPSaqM=
