[package]
name = "mn"
version = "0.1.0"
authors = ["Hawk Weisman <hi@hawkweisman.me>"]

[dependencies.mnemosyne-parser]
path = "parser"

[dependencies.mnemosyne]
path = "core"

[dependencies]
clap = "^1.2.5"
